// ----------------------------------------------------------------------------
//  FILE: CQCUninst_Constants.cpp
//  DATE: Tue, Jan 19 17:39:56 2021 -0500
//
//  This file was generated by the Charmed Quark CIDIDL compiler. Do not make
//  changes by hand, because they will be lost if the file is regenerated.
// ----------------------------------------------------------------------------

#include "CQCUninst.hpp"

const TString kCQCUninst::strTask_CQCVoiceAutoStart(L"Start CQC Voice");
const TString kCQCUninst::strTask_TrayAppAutoStart(L"Start CQC Tray Monitor");
