// ----------------------------------------------------------------------------
//  FILE: CQCIntfView_ExtCtrlServerBase.hpp
//  DATE: Fri, Feb 12 21:14:16 2021 -0500
//    ID: DC27C0F17755A031-863B6944077CC705
//
//  This file was generated by the Charmed Quark CIDIDL compiler. Do not make
//  changes by hand, because they will be lost if the file is regenerated.
// ----------------------------------------------------------------------------
#pragma once

#pragma CIDLIB_PACK(CIDLIBPACK)

class  TIntfCtrlServerBase : public TOrbServerBase
{
    public :
        // --------------------------------------------------------------------
        // Public, static data
        // --------------------------------------------------------------------
        static const TString strInterfaceId;
        static const TString strBinding;
        static const TString strScope;


        // --------------------------------------------------------------------
        // Constructors and destructor
        // --------------------------------------------------------------------
        TIntfCtrlServerBase(const TIntfCtrlServerBase&) = delete;
        TIntfCtrlServerBase(TIntfCtrlServerBase&&) = delete;
        ~TIntfCtrlServerBase();

        // --------------------------------------------------------------------
        // Public operators
        // --------------------------------------------------------------------
        TIntfCtrlServerBase& operator=(const TIntfCtrlServerBase&) = delete;
        TIntfCtrlServerBase& operator=(TIntfCtrlServerBase&&) = delete;

        // --------------------------------------------------------------------
        // Public, pure virtual methods
        // --------------------------------------------------------------------
        virtual tCIDLib::TBoolean bSpeakText
        (
            const TString& strToSpeak
        ) = 0;

        virtual tCIDLib::TCard4 c4Poll
        (
            COP TString& strBaseTmpl
            , COP TString& strTopTmpl
            , COP tCIDLib::TBoolean& bMaximized
        ) = 0;

        virtual tCIDLib::TVoid DoFrameOp
        (
            const tCQCKit::EIVFrmOps eOp
        ) = 0;

        virtual tCIDLib::TVoid DoMiscOp
        (
            const tCQCKit::EIVMiscOps eOp
        ) = 0;

        virtual tCIDLib::TVoid Invoke() = 0;

        virtual tCIDLib::TVoid LoadOverlay
        (
            const TString& strOvrName
            , const TString& strTmplName
        ) = 0;

        virtual tCIDLib::TVoid LoadTemplate
        (
            const TString& strTmplName
        ) = 0;

        virtual tCIDLib::TVoid Navigation
        (
            const tCQCKit::EScrNavOps eOp
        ) = 0;

        virtual tCIDLib::TVoid PlayWAV
        (
            const TString& strPath
        ) = 0;

        virtual tCIDLib::TVoid SetGlobalVar
        (
            const TString& strVarName
            , const TString& strValue
        ) = 0;

    protected :
        // --------------------------------------------------------------------
        // Hidden constructors
        // --------------------------------------------------------------------
        TIntfCtrlServerBase();
        TIntfCtrlServerBase(const TOrbObjId& ooidThis);

        // --------------------------------------------------------------------
        // Protected, inherited methods
        // --------------------------------------------------------------------
        tCIDLib::TVoid Dispatch
        (
            const  TString&      strMethodName
            ,      TOrbCmd&      orbcToDispatch
        )   override;

    private :
        // --------------------------------------------------------------------
        // Magic macros
        // --------------------------------------------------------------------
        RTTIDefs(TIntfCtrlServerBase,TOrbServerBase)
};

#pragma CIDLIB_POPPACK

