// ----------------------------------------------------------------------------
//  FILE: CQCEventSrv_ProtoServerBase.hpp
//  DATE: Wed, Jun 26 17:43:39 2019 -0400
//    ID: A57BF7129F2FC717-185A358D14B4D696
//
//  This file was generated by the Charmed Quark CIDIDL compiler. Do not make
//  changes by hand, because they will be lost if the file is regenerated.
// ----------------------------------------------------------------------------
#pragma once

#pragma CIDLIB_PACK(CIDLIBPACK)

class  TEventSrvServerBase : public TOrbServerBase
{
    public :
        // --------------------------------------------------------------------
        // Public, static data
        // --------------------------------------------------------------------
        static const TString strInterfaceId;
        static const TString strBinding;
        static const TString strRTVEventText;
        static const TString strCoreAdminBinding;


        // --------------------------------------------------------------------
        // Constructors and destructor
        // --------------------------------------------------------------------
        TEventSrvServerBase(const TEventSrvServerBase&) = delete;
        ~TEventSrvServerBase();

        // --------------------------------------------------------------------
        // Public operators
        // --------------------------------------------------------------------
        TEventSrvServerBase& operator=(const TEventSrvServerBase&) = delete;

        // --------------------------------------------------------------------
        // Public, pure virtual methods
        // --------------------------------------------------------------------
        virtual tCIDLib::TVoid DumpEvents
        (
            const TString& strTarFile
        ) = 0;

        virtual tCIDLib::TVoid AddEvent
        (
            const tCQCKit::EEvSrvTypes eEventType
            , const TString& strRelPath
            , tCIDLib::TCard4& c4ChangeSerNum
            , const TCQCSecToken& sectUser
        ) = 0;

        virtual tCIDLib::TVoid DeleteEvent
        (
            const tCQCKit::EEvSrvTypes eEventType
            , const TString& strRelPath
            , tCIDLib::TCard4& c4ChangeSerNum
            , const TCQCSecToken& sectUser
        ) = 0;

        virtual tCIDLib::TVoid PauseEvent
        (
            const tCQCKit::EEvSrvTypes eEventType
            , const TString& strRelPath
            , tCIDLib::TCard4& c4ChangeSerNum
            , const tCIDLib::TBoolean bPause
            , const TCQCSecToken& sectUser
        ) = 0;

        virtual tCIDLib::TVoid RenameEvent
        (
            const tCQCKit::EEvSrvTypes eEventType
            , const TString& strRelParPath
            , const TString& strOldName
            , const TString& strNewName
            , tCIDLib::TCard4& c4ChangeSerNum
            , const TCQCSecToken& sectUser
        ) = 0;

        virtual tCIDLib::TVoid RenameScope
        (
            const tCQCKit::EEvSrvTypes eEventType
            , const TString& strRelParPath
            , const TString& strOldName
            , const TString& strNewName
            , tCIDLib::TCard4& c4ChangeSerNum
            , const TCQCSecToken& sectUser
        ) = 0;

        virtual tCIDLib::TVoid UpdateEvent
        (
            const tCQCKit::EEvSrvTypes eEventType
            , const TString& strRelPath
            , tCIDLib::TCard4& c4ChangeSerNum
            , const TCQCSecToken& sectUser
        ) = 0;

        virtual tCIDLib::TVoid Ping() = 0;

        virtual tCIDLib::TVoid QueryPerEvInfo
        (
            const TString& strPath
            , tCQCKit::ESchTypes& eType
            , tCIDLib::TCard8& enctStart
            , tCIDLib::TCard4& c4Period
            , tCIDLib::TBoolean& bPaused
        ) = 0;

        virtual tCIDLib::TVoid QuerySchEvInfo
        (
            const TString& strPath
            , tCQCKit::ESchTypes& eType
            , tCIDLib::TCard4& c4Day
            , tCIDLib::TCard4& c4Hour
            , tCIDLib::TCard4& c4Minute
            , tCIDLib::TCard4& c4Mask
            , tCIDLib::TBoolean& bPaused
        ) = 0;

        virtual tCIDLib::TVoid QuerySunBasedEvInfo
        (
            const TString& strPath
            , tCIDLib::TInt4& i4Offset
            , tCIDLib::TBoolean& bPaused
        ) = 0;

        virtual tCIDLib::TVoid ReloadList
        (
            const tCQCKit::EEvSrvTypes eToReload
        ) = 0;

        virtual tCIDLib::TVoid SetLocInfo
        (
            const tCIDLib::TFloat8 f8Lat
            , const tCIDLib::TFloat8 f8Long
            , const TCQCSecToken& sectUser
        ) = 0;

    protected :
        // --------------------------------------------------------------------
        // Hidden constructors
        // --------------------------------------------------------------------
        TEventSrvServerBase();
        TEventSrvServerBase(const TOrbObjId& ooidThis);

        // --------------------------------------------------------------------
        // Protected, inherited methods
        // --------------------------------------------------------------------
        tCIDLib::TVoid Dispatch
        (
            const  TString&      strMethodName
            ,      TOrbCmd&      orbcToDispatch
        )   override;

    private :
        // --------------------------------------------------------------------
        // Magic macros
        // --------------------------------------------------------------------
        RTTIDefs(TEventSrvServerBase,TOrbServerBase)
};

#pragma CIDLIB_POPPACK

