@ECHO OFF

ECHO Blue Fantasy
CQCImgLoader /Cmd=Package /InFile=.\BlueFantasy /OutFile=%CQC_RESDIR%\ImgPacks\BlueFantasy

ECHO Bordello Images
CQCImgLoader /Cmd=Package /InFile=.\Bordello /OutFile=%CQC_RESDIR%\ImgPacks\Bordello

ECHO Clock Images
CQCImgLoader /Cmd=Package /InFile=.\Clocks /OutFile=%CQC_RESDIR%\ImgPacks\Clocks

ECHO Comcast Logos
CQCImgLoader /Cmd=Package /InFile=.\ComcastLogos /OutFile=%CQC_RESDIR%\ImgPacks\ComcastLogos

ECHO Echostar Images
CQCImgLoader /Cmd=Package /InFile=.\EchoStar /OutFile=%CQC_RESDIR%\ImgPacks\EchoStar

ECHO Elk M1 Images
CQCImgLoader /Cmd=Package /InFile=.\ElkImages /OutFile=%CQC_RESDIR%\ImgPacks\ElkM1

ECHO ExpressVu images
CQCImgLoader /Cmd=Package /InFile=.\ExpressVu /OutFile=%CQC_RESDIR%\ImgPacks\ExpressVu

ECHO Glyfx Vista images
CQCImgLoader /Cmd=Package /InFile=.\GlyfxVista /OutFile=%CQC_RESDIR%\ImgPacks\GlyfxVista

ECHO Krell Images
CQCImgLoader /Cmd=Package /InFile=.\KrellImages /OutFile=%CQC_RESDIR%\ImgPacks\Krell

ECHO Lillput Images
CQCImgLoader /Cmd=Package /InFile=.\Lilliput /OutFile=%CQC_RESDIR%\ImgPacks\Lilliput

ECHO Purple Jewel
CQCImgLoader /Cmd=Package /InFile=.\PurpleJewel /OutFile=%CQC_RESDIR%\ImgPacks\PurpleJewel

ECHO Ripper Gen Auto 1
CQCImgLoader /Cmd=Package /InFile=.\RipperAuto1 /OutFile=%CQC_RESDIR%\ImgPacks\RipperGenAuto1

ECHO Ron's Buttons
CQCImgLoader /Cmd=Package /InFile=.\RonsButtons /OutFile=%CQC_RESDIR%\ImgPacks\RonsButtons

ECHO Sharp 9000 Images
CQCImgLoader /Cmd=Package /InFile=.\Sharp9000 /OutFile=%CQC_RESDIR%\ImgPacks\Sharp9000

ECHO XBox 360 Images
CQCImgLoader /Cmd=Package /InFile=.\XBox360 /OutFile=%CQC_RESDIR%\ImgPacks\XBox360

ECHO Fancy Weather images
REM CQCImgLoader /Cmd=Package /InFile=.\FancyWeather /OutFile=%CQC_RESDIR%\ImgPacks\FancyWeather

ECHO Larger DTV logos
REM CQCImgLoader /Cmd=Package /InFile=.\DTVLogos /OutFile=%CQC_RESDIR%\ImgPacks\BigDTVLogos

