// ----------------------------------------------------------------------------
//  FILE: CQCWBHelper_CtrlServerBase.hpp
//  DATE: Fri, Feb 12 21:14:16 2021 -0500
//    ID: 897DB4F355CD673E-27AB212C9BA59D73
//
//  This file was generated by the Charmed Quark CIDIDL compiler. Do not make
//  changes by hand, because they will be lost if the file is regenerated.
// ----------------------------------------------------------------------------
#pragma once

#pragma CIDLIB_PACK(CIDLIBPACK)

class  TCQCWBHelperServerBase : public TOrbServerBase
{
    public :
        // --------------------------------------------------------------------
        // Public, static data
        // --------------------------------------------------------------------
        static const TString strInterfaceId;
        // --------------------------------------------------------------------
        // Constructors and destructor
        // --------------------------------------------------------------------
        TCQCWBHelperServerBase(const TCQCWBHelperServerBase&) = delete;
        TCQCWBHelperServerBase(TCQCWBHelperServerBase&&) = delete;
        ~TCQCWBHelperServerBase();

        // --------------------------------------------------------------------
        // Public operators
        // --------------------------------------------------------------------
        TCQCWBHelperServerBase& operator=(const TCQCWBHelperServerBase&) = delete;
        TCQCWBHelperServerBase& operator=(TCQCWBHelperServerBase&&) = delete;

        // --------------------------------------------------------------------
        // Public, pure virtual methods
        // --------------------------------------------------------------------
        virtual tCIDLib::TVoid Close() = 0;

        virtual tCIDLib::TVoid DoOp
        (
            const tWebBrowser::ENavOps eToDo
        ) = 0;

        virtual tCIDLib::TVoid Initialize
        (
            const TArea& areaPar
            , const TArea& areaWidget
            , const tCIDLib::TBoolean bVisibility
            , const TString& strInitURL
        ) = 0;

        virtual tCIDLib::TVoid Ping() = 0;

        virtual tCIDLib::TVoid SetArea
        (
            const TArea& areaPar
            , const TArea& areaWidget
        ) = 0;

        virtual tCIDLib::TVoid SetURL
        (
            const TString& strToSet
        ) = 0;

        virtual tCIDLib::TVoid SetVisibility
        (
            const tCIDLib::TBoolean bNewState
        ) = 0;

    protected :
        // --------------------------------------------------------------------
        // Hidden constructors
        // --------------------------------------------------------------------
        TCQCWBHelperServerBase();
        TCQCWBHelperServerBase(const TOrbObjId& ooidThis);

        // --------------------------------------------------------------------
        // Protected, inherited methods
        // --------------------------------------------------------------------
        tCIDLib::TVoid Dispatch
        (
            const  TString&      strMethodName
            ,      TOrbCmd&      orbcToDispatch
        )   override;

    private :
        // --------------------------------------------------------------------
        // Magic macros
        // --------------------------------------------------------------------
        RTTIDefs(TCQCWBHelperServerBase,TOrbServerBase)
};

#pragma CIDLIB_POPPACK

