// ----------------------------------------------------------------------------
//  FILE: CQCIR_RepoClientProxy.hpp
//  DATE: Tue, Jan 19 17:39:55 2021 -0500
//    ID: E2ABEBB0AA4D1186-3412D00C17FA509A
//
//  This file was generated by the Charmed Quark CIDIDL compiler. Do not make
//  changes by hand, because they will be lost if the file is regenerated.
// ----------------------------------------------------------------------------
#pragma once

#pragma CIDLIB_PACK(CIDLIBPACK)

class CQCIREXPORT TIRRepoClientProxy : public TOrbClientBase
{
    public :
        // --------------------------------------------------------------------
        // Public, static data
        // --------------------------------------------------------------------
        static const TString strInterfaceId;
        static const TString strBinding;



        // --------------------------------------------------------------------
        // Public Constructors and Destructor
        // --------------------------------------------------------------------
        TIRRepoClientProxy();
        TIRRepoClientProxy(const TOrbObjId& ooidSrc, const TString& strNSBinding);
        TIRRepoClientProxy(const TIRRepoClientProxy&) = delete;
        TIRRepoClientProxy(TIRRepoClientProxy&&) = delete;
        ~TIRRepoClientProxy();

        // --------------------------------------------------------------------
        // Public operators
        // --------------------------------------------------------------------
        TIRRepoClientProxy& operator=(const TIRRepoClientProxy&) = delete;
        TIRRepoClientProxy& operator=(TIRRepoClientProxy&&) = delete;

        // --------------------------------------------------------------------
        // Public, inherited methods
        // --------------------------------------------------------------------
        tCIDLib::TVoid SetObjId
        (
            const   TOrbObjId& ooidToSet
            , const TString& strNSBinding
            , const tCIDLib::TBoolean bCheck = kCIDLib::True
        )   override;

        // --------------------------------------------------------------------
        // Public, non-virtual methods
        // --------------------------------------------------------------------
        tCIDLib::TBoolean bModelExists
        (
            const TString& strDevModel
            , const TString& strBlasterName
        );

        tCIDLib::TCard4 c4QueryDevCatList
        (
            const tCQCKit::EDevCats eCategory
            , const TString& strBlasterName
            , TVector<TIRBlasterDevModelInfo>& colToFill
        );

        tCIDLib::TCard4 c4QueryDevModelList
        (
            const TString& strBlasterName
            , TVector<TIRBlasterDevModelInfo>& colToFill
        );

        tCIDLib::TVoid DeleteDevModel
        (
            const TString& strDevModel
            , const TString& strBlasterName
        );

        tCIDLib::TVoid QueryDevModel
        (
            const TString& strDevModel
            , const TString& strBlasterName
            , TIRBlasterDevModel& irbdmToFill
        );

        tCIDLib::TVoid WriteDevModel
        (
            const TString& strDevModel
            , const TString& strBlasterName
            , const TIRBlasterDevModel& irbdmToWrite
        );

    protected :
        // --------------------------------------------------------------------
        // Declare our friends
        // --------------------------------------------------------------------
        friend class TFacCIDOrb;

    private :
        // --------------------------------------------------------------------
        // Magic macros
        // --------------------------------------------------------------------
        RTTIDefs(TIRRepoClientProxy,TOrbClientBase)
};

#pragma CIDLIB_POPPACK

inline tCIDLib::TVoid
TIRRepoClientProxy::SetObjId(const  TOrbObjId& ooidToSet
              , const TString& strNSBinding
              , const tCIDLib::TBoolean bCheck)
{
    TParent::SetObjId(ooidToSet, strNSBinding, bCheck);
}

