@ECHO OFF
SETLOCAL
SET APPCMD=XMLGatewayTest.exe /User=%CQC_USERNAME% /Password=%CQC_PASSWORD%

IF "%1"=="debug" GOTO DO_DEBUG
GOTO DO_NON_DEBUG

:DO_DEBUG
devenv /debugexe %CID_RESDIR%\%APPCMD%
GOTO END

: DO_NON_DEBUG
%APPCMD%

:END
