// ----------------------------------------------------------------------------
//  FILE: CQCKit_InstClientProxy.hpp
//  DATE: Sun, Nov 29 14:26:12 2020 -0500
//    ID: 825C0E370D8C5D6C-0B3B6D941AB56445
//
//  This file was generated by the Charmed Quark CIDIDL compiler. Do not make
//  changes by hand, because they will be lost if the file is regenerated.
// ----------------------------------------------------------------------------
#pragma once

#pragma CIDLIB_PACK(CIDLIBPACK)

class CQCKITEXPORT TCQCInstClientProxy : public TOrbClientBase
{
    public :
        // --------------------------------------------------------------------
        // Public, static data
        // --------------------------------------------------------------------
        static const TString strInterfaceId;
        static const TString strBinding;



        // --------------------------------------------------------------------
        // Public Constructors and Destructor
        // --------------------------------------------------------------------
        TCQCInstClientProxy();
        TCQCInstClientProxy(const TOrbObjId& ooidSrc, const TString& strNSBinding);
        TCQCInstClientProxy(const TCQCInstClientProxy&) = delete;
        TCQCInstClientProxy(TCQCInstClientProxy&&) = delete;
        ~TCQCInstClientProxy();

        // --------------------------------------------------------------------
        // Public operators
        // --------------------------------------------------------------------
        TCQCInstClientProxy& operator=(const TCQCInstClientProxy&) = delete;
        TCQCInstClientProxy& operator=(TCQCInstClientProxy&&) = delete;

        // --------------------------------------------------------------------
        // Public, inherited methods
        // --------------------------------------------------------------------
        tCIDLib::TVoid SetObjId
        (
            const   TOrbObjId& ooidToSet
            , const TString& strNSBinding
            , const tCIDLib::TBoolean bCheck = kCIDLib::True
        )   override;

        // --------------------------------------------------------------------
        // Public, non-virtual methods
        // --------------------------------------------------------------------
        tCIDLib::TBoolean bAddOrUpdateCheatSheet
        (
            const TString& strUserName
            , tCIDLib::TCard4& c4SerialNum
            , const TCQCActVarList& cavlCheatSheet
            , const TCQCSecToken& sectUser
        );

        tCIDLib::TBoolean bUpdateEmailAccount
        (
            const TCQCEMailAccount& emacctToAdd
            , tCIDLib::TCard4& c4SerialNum
            , const TCQCSecToken& sectUser
            , const tCIDLib::TBoolean bMustBeNew
        );

        tCIDLib::TBoolean bAddOrUpdateGC100Cfg
        (
            const tCIDLib::TCard4 c4BufSz_mbufToSet
            , const THeapBuf& mbufToSet
            , tCIDLib::TCard4& c4SerialNum
            , const TCQCSecToken& sectUser
        );

        tCIDLib::TBoolean bAddOrUpdateJAPCfg
        (
            const tCIDLib::TCard4 c4BufSz_mbufToFill
            , const THeapBuf& mbufToFill
            , tCIDLib::TCard4& c4SerialNum
            , const TCQCSecToken& sectUser
        );

        tCIDLib::TBoolean bDeleteEMailAccount
        (
            const TString& strAccount
            , const TCQCSecToken& sectUser
        );

        tCIDLib::TBoolean bDrvCfgDriverPresent
        (
            const TString& strMoniker
            , TString& strHost
            , const TCQCSecToken& sectUser
        );

        tCIDLib::TBoolean bDrvCfgMoveDrivers
        (
            const TString& strOldHost
            , const TString& strNewHost
            , TVector<TString>& colMsgs
            , const TCQCSecToken& sectUser
        );

        tCIDLib::TBoolean bDrvCfgQueryConfig
        (
            tCIDLib::TCard4& c4Version
            , const TString& strMoniker
            , TString& strHost
            , TCQCDriverObjCfg& cqcdcToFill
            , const TCQCSecToken& sectUser
        );

        tCIDLib::TBoolean bDrvCfgQueryHostConfigs
        (
            tCIDLib::TCard4& c4Version
            , const TString& strHost
            , TVector<TCQCDriverObjCfg>& colCfgs
            , TFundVector<tCIDLib::TCard4>& fcolCfgVers
            , const TCQCSecToken& sectUser
        );

        tCIDLib::TBoolean bDrvCfgQueryHosts
        (
            TVector<TString>& colHosts
            , const TCQCSecToken& sectUser
        );

        tCIDLib::TBoolean bDrvCfgQueryMonList
        (
            tCIDLib::TCard4& c4Version
            , const TString& strHost
            , TVector<TString>& colToFill
            , TFundVector<tCIDLib::TCard4>& fcolVers
            , TFundVector<tCIDLib::TBoolean>& fcolClDrvs
            , const TCQCSecToken& sectUser
        );

        tCIDLib::TBoolean bDrvCfgQueryMonList
        (
            TVector<TKeyValuePair>& colToFill
            , const TCQCSecToken& sectUser
        );

        tCIDLib::TBoolean bDrvCfgSetPause
        (
            const TString& strMoniker
            , const tCIDLib::TBoolean bNewState
            , tCIDLib::TCard4& c4NewVersion
            , const TCQCSecToken& sectUser
        );

        tCIDLib::TBoolean bQueryCheatSheet
        (
            tCIDLib::TCard4& c4SerialNum
            , tCIDLib::ELoadRes& eLoadRes
            , const TString& strUserName
            , TCQCActVarList& cavlCheatSheet
            , const TCQCSecToken& sectUser
        );

        tCIDLib::TBoolean bQueryDrvManifest
        (
            const TString& strMake
            , const TString& strModel
            , TCQCDriverCfg& cqcdcToFill
        );

        tCIDLib::TBoolean bQueryEmailAccount
        (
            const TString& strAccount
            , TCQCEMailAccount& emacctToFill
            , const tCIDLib::TBoolean bThrowIfNot
            , const TCQCSecToken& sectUser
        );

        tCIDLib::TBoolean bQueryEMailAccountNames
        (
            TVector<TString>& colToFill
            , const TCQCSecToken& sectUser
        );

        tCIDLib::TBoolean bQueryKeyMap
        (
            tCIDLib::TCard4& c4SerialNum
            , tCIDLib::ELoadRes& eLoadRes
            , const TString& strUserName
            , TCQCKeyMap& kmToFill
            , const TCQCSecToken& sectUser
        );

        tCIDLib::TBoolean bQueryLocationInfo
        (
            tCIDLib::TFloat8& f8Lat
            , tCIDLib::TFloat8& f8Long
            , const TCQCSecToken& sectUser
        );

        tCIDLib::TBoolean bQueryProtoFile
        (
            const TString& strFileName
            , tCIDLib::TCard4& c4BufSz_mbufToFill
            , THeapBuf& mbufToFill
        );

        tCIDLib::TBoolean bQueryZWDIIndex
        (
            tCIDLib::TCard4& c4BufSz_mbufIndex
            , THeapBuf& mbufIndex
            , tCIDLib::TCard4& c4BufSz_mbufDTD
            , THeapBuf& mbufDTD
        );

        tCIDLib::TBoolean bQueryZWDIFile
        (
            const TString& strFileName
            , tCIDLib::TCard4& c4BufSz_mbufData
            , THeapBuf& mbufData
        );

        tCIDLib::TCard4 c4QueryDrvManifests
        (
            TVector<TCQCDriverCfg>& colToFill
            , const TCQCSecToken& sectUser
        );

        tCIDLib::TVoid DrvCfgQueryDrvsInfo
        (
            TVector<TString>& colMonikers
            , TVector<TString>& colMakes
            , TVector<TString>& colModels
            , TFundVector<tCQCKit::EDevCats>& fcolCats
            , const TCQCSecToken& sectUser
        );

        tCIDLib::TVoid DrvCfgRemoveDrv
        (
            const TString& strMoniker
            , const TString& strHost
            , tCIDLib::TCard4& c4NewVersion
            , const TCQCSecToken& sectUser
        );

        tCIDLib::TVoid DrvCfgQueryReportInfo
        (
            TVector<TKeyValues>& colToFill
            , const TCQCSecToken& sectUser
        );

        tCIDLib::TVoid DrvCfgSetConfig
        (
            const TString& strMoniker
            , const TString& strHost
            , const TCQCDriverObjCfg& cqcdcToSet
            , const tCIDLib::TBoolean bNewDriver
            , tCIDLib::TCard4& c4NewVersion
            , const TCQCSecToken& sectUser
        );

        tCIDLib::ELoadRes eQueryGC100Cfg
        (
            tCIDLib::TCard4& c4SerialNum
            , tCIDLib::TCard4& c4BufSz_mbufToFill
            , THeapBuf& mbufToFill
            , const TCQCSecToken& sectUser
        );

        tCIDLib::ELoadRes eQueryJAPCfg
        (
            tCIDLib::TCard4& c4SerialNum
            , tCIDLib::TCard4& c4BufSz_mbufToFill
            , THeapBuf& mbufToFill
            , const TCQCSecToken& sectUser
        );

        tCIDLib::TVoid Ping();

        tCIDLib::TVoid QueryVoiceFiles
        (
            tCIDLib::TCard4& c4BufSz_mbufTree
            , THeapBuf& mbufTree
            , tCIDLib::TCard4& c4BufSz_mbufGrammar
            , THeapBuf& mbufGrammar
        );

        tCIDLib::TVoid RenameEMailAccount
        (
            const TString& strOldName
            , const TString& strNewName
            , const TCQCSecToken& sectUser
        );

        tCIDLib::TVoid SetKeyMap
        (
            const TString& strUserName
            , const TCQCKeyMap& kmToSEt
            , const TCQCSecToken& sectUser
        );

        tCIDLib::TBoolean SetLocationInfo
        (
            const tCIDLib::TFloat8 f8Lat
            , const tCIDLib::TFloat8 f8Long
            , const TCQCSecToken& sectUser
        );

        tCIDLib::TVoid UploadProtocol
        (
            const TString& strFileName
            , const tCIDLib::TCard4 c4BufSz_mbufText
            , const THeapBuf& mbufText
            , const tCIDLib::TBoolean bSystem
            , const TCQCSecToken& sectUser
        );

        tCIDLib::TVoid UploadManifest
        (
            const TString& strFileName
            , const tCIDLib::TCard4 c4BufSz_mbufText
            , const THeapBuf& mbufText
            , const tCIDLib::TBoolean bSystem
            , const TCQCSecToken& sectUser
        );

    protected :
        // --------------------------------------------------------------------
        // Declare our friends
        // --------------------------------------------------------------------
        friend class TFacCIDOrb;

    private :
        // --------------------------------------------------------------------
        // Magic macros
        // --------------------------------------------------------------------
        RTTIDefs(TCQCInstClientProxy,TOrbClientBase)
};

#pragma CIDLIB_POPPACK

inline tCIDLib::TVoid
TCQCInstClientProxy::SetObjId(const  TOrbObjId& ooidToSet
              , const TString& strNSBinding
              , const tCIDLib::TBoolean bCheck)
{
    TParent::SetObjId(ooidToSet, strNSBinding, bCheck);
}

