// ----------------------------------------------------------------------------
//  FILE: iTunesRepoTMS_iTRepoIntfClientProxy.hpp
//  DATE: Fri, Feb 14 18:49:47 2020 -0500
//    ID: 5A2C99C79FD12115-189DB6E5BAA86FBF
//
//  This file was generated by the Charmed Quark CIDIDL compiler. Do not make
//  changes by hand, because they will be lost if the file is regenerated.
// ----------------------------------------------------------------------------
#pragma once

#pragma CIDLIB_PACK(CIDLIBPACK)

class  TiTRepoIntfClientProxy : public TOrbClientBase
{
    public :
        // --------------------------------------------------------------------
        // Public, static data
        // --------------------------------------------------------------------
        static const TString strInterfaceId;
        static const TString strImplScope;
        static const TString strImplBinding;



        // --------------------------------------------------------------------
        // Public Constructors and Destructor
        // --------------------------------------------------------------------
        TiTRepoIntfClientProxy();
        TiTRepoIntfClientProxy(const TOrbObjId& ooidSrc, const TString& strNSBinding);
        TiTRepoIntfClientProxy(const TiTRepoIntfClientProxy&) = delete;
        TiTRepoIntfClientProxy(TiTRepoIntfClientProxy&&) = delete;
        ~TiTRepoIntfClientProxy();

        // --------------------------------------------------------------------
        // Public operators
        // --------------------------------------------------------------------
        TiTRepoIntfClientProxy& operator=(const TiTRepoIntfClientProxy&) = delete;
        TiTRepoIntfClientProxy& operator=(TiTRepoIntfClientProxy&&) = delete;

        // --------------------------------------------------------------------
        // Public, inherited methods
        // --------------------------------------------------------------------
        tCIDLib::TVoid SetObjId
        (
            const   TOrbObjId& ooidToSet
            , const TString& strNSBinding
            , const tCIDLib::TBoolean bCheck = kCIDLib::True
        )   override;

        // --------------------------------------------------------------------
        // Public, non-virtual methods
        // --------------------------------------------------------------------
        tCIDLib::TBoolean bQueryData
        (
            const TString& strQueryType
            , const TString& strDataName
            , tCIDLib::TCard4& c4BufSz_mbufToFill
            , THeapBuf& mbufToFill
        );

        tCIDLib::TBoolean bQueryData2
        (
            const TString& strQueryType
            , tCIDLib::TCard4& c4BufSz_mbufIO
            , THeapBuf& mbufIO
        );

        tCIDLib::TBoolean bQueryTextVal
        (
            const TString& strQueryType
            , const TString& strDataName
            , TString& strToFill
        );

        tCIDLib::TBoolean bSendData
        (
            const TString& strSendType
            , TString& strDataName
            , tCIDLib::TCard4& c4BufSz_mbufToSend
            , THeapBuf& mbufToSend
        );

        tCIDLib::TCard4 c4QueryVal
        (
            const TString& strValId
        );

        tCIDLib::TCard4 c4SendCmd
        (
            const TString& strCmdId
            , const TString& strParms
        );

        tCIDLib::TVoid QueryStatus
        (
            tCQCMedia::ELoadStatus& eCurStatus
            , tCQCMedia::ELoadStatus& eLoadStatus
            , TString& strDBSerialNum
            , tCIDLib::TCard4& c4TitleCnt
        );

        tCIDLib::TBoolean bReloadDB();

    protected :
        // --------------------------------------------------------------------
        // Declare our friends
        // --------------------------------------------------------------------
        friend class TFacCIDOrb;

    private :
        // --------------------------------------------------------------------
        // Magic macros
        // --------------------------------------------------------------------
        RTTIDefs(TiTRepoIntfClientProxy,TOrbClientBase)
};

#pragma CIDLIB_POPPACK

inline tCIDLib::TVoid
TiTRepoIntfClientProxy::SetObjId(const  TOrbObjId& ooidToSet
              , const TString& strNSBinding
              , const tCIDLib::TBoolean bCheck)
{
    TParent::SetObjId(ooidToSet, strNSBinding, bCheck);
}

