// ----------------------------------------------------------------------------
//  FILE: CQCDataSrv_InstServerBase.hpp
//  DATE: Fri, Feb 12 21:14:15 2021 -0500
//    ID: 825C0E370D8C5D6C-0B3B6D941AB56445
//
//  This file was generated by the Charmed Quark CIDIDL compiler. Do not make
//  changes by hand, because they will be lost if the file is regenerated.
// ----------------------------------------------------------------------------
#pragma once

#pragma CIDLIB_PACK(CIDLIBPACK)

class  TCQCInstServerBase : public TOrbServerBase
{
    public :
        // --------------------------------------------------------------------
        // Public, static data
        // --------------------------------------------------------------------
        static const TString strInterfaceId;
        static const TString strBinding;


        // --------------------------------------------------------------------
        // Constructors and destructor
        // --------------------------------------------------------------------
        TCQCInstServerBase(const TCQCInstServerBase&) = delete;
        TCQCInstServerBase(TCQCInstServerBase&&) = delete;
        ~TCQCInstServerBase();

        // --------------------------------------------------------------------
        // Public operators
        // --------------------------------------------------------------------
        TCQCInstServerBase& operator=(const TCQCInstServerBase&) = delete;
        TCQCInstServerBase& operator=(TCQCInstServerBase&&) = delete;

        // --------------------------------------------------------------------
        // Public, pure virtual methods
        // --------------------------------------------------------------------
        virtual tCIDLib::TBoolean bAddOrUpdateCheatSheet
        (
            const TString& strUserName
            , CIOP tCIDLib::TCard4& c4SerialNum
            , const TCQCActVarList& cavlCheatSheet
            , const TCQCSecToken& sectUser
        ) = 0;

        virtual tCIDLib::TBoolean bUpdateEmailAccount
        (
            const TCQCEMailAccount& emacctToAdd
            , CIOP tCIDLib::TCard4& c4SerialNum
            , const TCQCSecToken& sectUser
            , const tCIDLib::TBoolean bMustBeNew
        ) = 0;

        virtual tCIDLib::TBoolean bAddOrUpdateGC100Cfg
        (
            const tCIDLib::TCard4 c4BufSz_mbufToSet
            , const THeapBuf& mbufToSet
            , CIOP tCIDLib::TCard4& c4SerialNum
            , const TCQCSecToken& sectUser
        ) = 0;

        virtual tCIDLib::TBoolean bAddOrUpdateJAPCfg
        (
            const tCIDLib::TCard4 c4BufSz_mbufToFill
            , const THeapBuf& mbufToFill
            , CIOP tCIDLib::TCard4& c4SerialNum
            , const TCQCSecToken& sectUser
        ) = 0;

        virtual tCIDLib::TBoolean bDeleteEMailAccount
        (
            const TString& strAccount
            , const TCQCSecToken& sectUser
        ) = 0;

        virtual tCIDLib::TBoolean bDrvCfgDriverPresent
        (
            const TString& strMoniker
            , COP TString& strHost
            , const TCQCSecToken& sectUser
        ) = 0;

        virtual tCIDLib::TBoolean bDrvCfgMoveDrivers
        (
            const TString& strOldHost
            , const TString& strNewHost
            , COP TVector<TString>& colMsgs
            , const TCQCSecToken& sectUser
        ) = 0;

        virtual tCIDLib::TBoolean bDrvCfgQueryConfig
        (
            CIOP tCIDLib::TCard4& c4Version
            , const TString& strMoniker
            , CIOP TString& strHost
            , TCQCDriverObjCfg& cqcdcToFill
            , const TCQCSecToken& sectUser
        ) = 0;

        virtual tCIDLib::TBoolean bDrvCfgQueryHostConfigs
        (
            CIOP tCIDLib::TCard4& c4Version
            , const TString& strHost
            , TVector<TCQCDriverObjCfg>& colCfgs
            , TFundVector<tCIDLib::TCard4>& fcolCfgVers
            , const TCQCSecToken& sectUser
        ) = 0;

        virtual tCIDLib::TBoolean bDrvCfgQueryHosts
        (
            COP TVector<TString>& colHosts
            , const TCQCSecToken& sectUser
        ) = 0;

        virtual tCIDLib::TBoolean bDrvCfgQueryMonList
        (
            CIOP tCIDLib::TCard4& c4Version
            , const TString& strHost
            , TVector<TString>& colToFill
            , TFundVector<tCIDLib::TCard4>& fcolVers
            , TFundVector<tCIDLib::TBoolean>& fcolClDrvs
            , const TCQCSecToken& sectUser
        ) = 0;

        virtual tCIDLib::TBoolean bDrvCfgQueryMonList
        (
            COP TVector<TKeyValuePair>& colToFill
            , const TCQCSecToken& sectUser
        ) = 0;

        virtual tCIDLib::TBoolean bDrvCfgSetPause
        (
            const TString& strMoniker
            , const tCIDLib::TBoolean bNewState
            , COP tCIDLib::TCard4& c4NewVersion
            , const TCQCSecToken& sectUser
        ) = 0;

        virtual tCIDLib::TBoolean bQueryCheatSheet
        (
            CIOP tCIDLib::TCard4& c4SerialNum
            , tCIDLib::ELoadRes& eLoadRes
            , const TString& strUserName
            , TCQCActVarList& cavlCheatSheet
            , const TCQCSecToken& sectUser
        ) = 0;

        virtual tCIDLib::TBoolean bQueryDrvManifest
        (
            const TString& strMake
            , const TString& strModel
            , COP TCQCDriverCfg& cqcdcToFill
        ) = 0;

        virtual tCIDLib::TBoolean bQueryEmailAccount
        (
            const TString& strAccount
            , COP TCQCEMailAccount& emacctToFill
            , const tCIDLib::TBoolean bThrowIfNot
            , const TCQCSecToken& sectUser
        ) = 0;

        virtual tCIDLib::TBoolean bQueryEMailAccountNames
        (
            COP TVector<TString>& colToFill
            , const TCQCSecToken& sectUser
        ) = 0;

        virtual tCIDLib::TBoolean bQueryKeyMap
        (
            CIOP tCIDLib::TCard4& c4SerialNum
            , tCIDLib::ELoadRes& eLoadRes
            , const TString& strUserName
            , TCQCKeyMap& kmToFill
            , const TCQCSecToken& sectUser
        ) = 0;

        virtual tCIDLib::TBoolean bQueryLocationInfo
        (
            COP tCIDLib::TFloat8& f8Lat
            , COP tCIDLib::TFloat8& f8Long
            , const TCQCSecToken& sectUser
        ) = 0;

        virtual tCIDLib::TBoolean bQueryProtoFile
        (
            const TString& strFileName
            , tCIDLib::TCard4& c4BufSz_mbufToFill
            , COP THeapBuf& mbufToFill
        ) = 0;

        virtual tCIDLib::TBoolean bQueryZWDIIndex
        (
            tCIDLib::TCard4& c4BufSz_mbufIndex
            , COP THeapBuf& mbufIndex
            , tCIDLib::TCard4& c4BufSz_mbufDTD
            , COP THeapBuf& mbufDTD
        ) = 0;

        virtual tCIDLib::TBoolean bQueryZWDIFile
        (
            const TString& strFileName
            , tCIDLib::TCard4& c4BufSz_mbufData
            , COP THeapBuf& mbufData
        ) = 0;

        virtual tCIDLib::TCard4 c4QueryDrvManifests
        (
            COP TVector<TCQCDriverCfg>& colToFill
            , const TCQCSecToken& sectUser
        ) = 0;

        virtual tCIDLib::TVoid DrvCfgQueryDrvsInfo
        (
            COP TVector<TString>& colMonikers
            , COP TVector<TString>& colMakes
            , COP TVector<TString>& colModels
            , COP TFundVector<tCQCKit::EDevCats>& fcolCats
            , const TCQCSecToken& sectUser
        ) = 0;

        virtual tCIDLib::TVoid DrvCfgRemoveDrv
        (
            const TString& strMoniker
            , const TString& strHost
            , COP tCIDLib::TCard4& c4NewVersion
            , const TCQCSecToken& sectUser
        ) = 0;

        virtual tCIDLib::TVoid DrvCfgQueryReportInfo
        (
            COP TVector<TKeyValues>& colToFill
            , const TCQCSecToken& sectUser
        ) = 0;

        virtual tCIDLib::TVoid DrvCfgSetConfig
        (
            const TString& strMoniker
            , const TString& strHost
            , const TCQCDriverObjCfg& cqcdcToSet
            , const tCIDLib::TBoolean bNewDriver
            , COP tCIDLib::TCard4& c4NewVersion
            , const TCQCSecToken& sectUser
        ) = 0;

        virtual tCIDLib::ELoadRes eQueryGC100Cfg
        (
            CIOP tCIDLib::TCard4& c4SerialNum
            , tCIDLib::TCard4& c4BufSz_mbufToFill
            , COP THeapBuf& mbufToFill
            , const TCQCSecToken& sectUser
        ) = 0;

        virtual tCIDLib::ELoadRes eQueryJAPCfg
        (
            CIOP tCIDLib::TCard4& c4SerialNum
            , tCIDLib::TCard4& c4BufSz_mbufToFill
            , COP THeapBuf& mbufToFill
            , const TCQCSecToken& sectUser
        ) = 0;

        virtual tCIDLib::TVoid Ping() = 0;

        virtual tCIDLib::TVoid QueryVoiceFiles
        (
            tCIDLib::TCard4& c4BufSz_mbufTree
            , COP THeapBuf& mbufTree
            , tCIDLib::TCard4& c4BufSz_mbufGrammar
            , COP THeapBuf& mbufGrammar
        ) = 0;

        virtual tCIDLib::TVoid RenameEMailAccount
        (
            const TString& strOldName
            , const TString& strNewName
            , const TCQCSecToken& sectUser
        ) = 0;

        virtual tCIDLib::TVoid SetKeyMap
        (
            const TString& strUserName
            , const TCQCKeyMap& kmToSEt
            , const TCQCSecToken& sectUser
        ) = 0;

        virtual tCIDLib::TBoolean SetLocationInfo
        (
            const tCIDLib::TFloat8 f8Lat
            , const tCIDLib::TFloat8 f8Long
            , const TCQCSecToken& sectUser
        ) = 0;

        virtual tCIDLib::TVoid UploadProtocol
        (
            const TString& strFileName
            , const tCIDLib::TCard4 c4BufSz_mbufText
            , const THeapBuf& mbufText
            , const tCIDLib::TBoolean bSystem
            , const TCQCSecToken& sectUser
        ) = 0;

        virtual tCIDLib::TVoid UploadManifest
        (
            const TString& strFileName
            , const tCIDLib::TCard4 c4BufSz_mbufText
            , const THeapBuf& mbufText
            , const tCIDLib::TBoolean bSystem
            , const TCQCSecToken& sectUser
        ) = 0;

    protected :
        // --------------------------------------------------------------------
        // Hidden constructors
        // --------------------------------------------------------------------
        TCQCInstServerBase();
        TCQCInstServerBase(const TOrbObjId& ooidThis);

        // --------------------------------------------------------------------
        // Protected, inherited methods
        // --------------------------------------------------------------------
        tCIDLib::TVoid Dispatch
        (
            const  TString&      strMethodName
            ,      TOrbCmd&      orbcToDispatch
        )   override;

    private :
        // --------------------------------------------------------------------
        // Magic macros
        // --------------------------------------------------------------------
        RTTIDefs(TCQCInstServerBase,TOrbServerBase)
};

#pragma CIDLIB_POPPACK

