IF NOT EXIST %CQC_RESDIR%\%1C_%CQC_CIDLIBVER%.DLL GOTO NO_CLIENT
COPY %CQC_RESDIR%\%1C_%CQC_CIDLIBVER%.Dll %TARGET_IMG%\Image\CQC\ > Nul
:NO_CLIENT

IF NOT EXIST %CQC_RESDIR%\%1C_%CQC_CIDLIBVER%_en.CIDMsg GOTO NO_CLIENTMSG
COPY %CQC_RESDIR%\%1C_%CQC_CIDLIBVER%_en.CIDMsg %TARGET_IMG%\Image\CQC\ > Nul
:NO_CLIENTMSG

IF NOT EXIST %CQC_RESDIR%\%1C_%CQC_CIDLIBVER%.CIDRes GOTO NO_CLIENTRES
COPY %CQC_RESDIR%\%1C_%CQC_CIDLIBVER%.CIDRes %TARGET_IMG%\Image\CQC\ > Nul
:NO_CLIENTRES

IF NOT EXIST %CQC_RESDIR%\%1S_%CQC_CIDLIBVER%.DLL GOTO NO_SERVER
COPY %CQC_RESDIR%\%1S_%CQC_CIDLIBVER%.Dll %TARGET_IMG%\Image\CQC\ > Nul
:NO_SERVER

IF NOT EXIST %CQC_RESDIR%\%1S_%CQC_CIDLIBVER%_en.CIDMsg GOTO NO_SERVERMSG
COPY %CQC_RESDIR%\%1S_%CQC_CIDLIBVER%_en.CIDMsg %TARGET_IMG%\Image\CQC\ > Nul
:NO_SERVERMSG

IF "%2"=="" GOTO DONE
COPY %CQC_RESDIR%\%2_%CQC_CIDLIBVER%.Dll %TARGET_IMG%\Image\CQC\ > Nul
COPY %CQC_RESDIR%\%2_%CQC_CIDLIBVER%_en.CIDMsg %TARGET_IMG%\Image\CQC\ > Nul

IF "%3"=="" GOTO DONE
COPY %CQC_RESDIR%\%3_%CQC_CIDLIBVER%.Dll %TARGET_IMG%\Image\CQC\ > Nul
COPY %CQC_RESDIR%\%3_%CQC_CIDLIBVER%_en.CIDMsg %TARGET_IMG%\Image\CQC\ > Nul

:DONE

