IF NOT EXIST %CQC_RESDIR%\%1*.DLL GOTO NO_CLIENT
COPY %CQC_RESDIR%\%1*.Dll %TARGET_IMG%\Image\CQC\ > Nul
COPY %CQC_RESDIR%\%1*.CIDMsg %TARGET_IMG%\Image\CQC\ > Nul
:NO_CLIENT

IF NOT EXIST %CQC_RESDIR%\%1*.CIDRes GOTO NO_CLIENTRES
COPY %CQC_RESDIR%\%1*.CIDRes %TARGET_IMG%\Image\CQC\ > Nul
:NO_CLIENTRES

IF "%2"=="" GOTO DONE
COPY %CQC_RESDIR%\%2*.Dll %TARGET_IMG%\Image\CQC\ > Nul
COPY %CQC_RESDIR%\%2*.CIDMsg %TARGET_IMG%\Image\CQC\ > Nul

IF "%3"=="" GOTO DONE
COPY %CQC_RESDIR%\%3*.Dll %TARGET_IMG%\Image\CQC\ > Nul
COPY %CQC_RESDIR%\%3*.CIDMsg %TARGET_IMG%\Image\CQC\ > Nul

:DONE
